### ISSUE TITLE
Consider adding pgvector extension

### ISSUE THREAD

**Issue by ccjernigan** [fly-apps/postgres-ha#112]
[pgvector](https://github.com/pgvector/pgvector) enables vector similarity search which is useful for AI applications.  Support exists in Azure, AWS, and Supabase for this extension, indicating it is growing in popularity.

I had originally hoped to use Upstash Redis on Fly.io for a similarity search, but Upstash Redis does not support this functionality yet.  (Redis has the RediSearch extension for vector similarity search).

Pgvector support provides another way to achieve this.

**Comment by lubien** [comment]
Thanks for reaching out on this, this is our old postgres version we are now at: https://github.com/fly-apps/postgres-flex

In the meantime, Jason has a quick tutorial on how to add PGVector to PG Flex: https://community.fly.io/t/adding-pgvector-to-fly-postgres/12202

**Comment by ccjernigan** [comment]
Thanks for the reply and the tutorial.  I'll re-file this issue in the new repo.
