### ISSUE TITLE
Set STOLONCTL environment variables

### ISSUE THREAD

**Issue by davissp14** [fly-apps/postgres-ha#13]
`stolonctl` is an invaluable tool, but the commands are currently very tedious to construct.  We can make this easier by setting the necessary STOLONCTL environment variables at provision time.

https://github.com/sorintlab/stolon/blob/master/doc/stolonctl.md

**Comment by davissp14** [comment]
Quick and dirty way to get this working:

```
  fly ssh console --app <app-name>
  export $(cat /data/.env | xargs)
  
  stolonctl status
```

**Comment by anacrolix** [comment]
Thank you for reporting this. Helped me figure out how to fix some issues with stolon!

**Comment by tv42** [comment]
Those could be set by default in the shell, or at the very least this needs to be documented.

It was only after I found this issue that I was able to force a failover.
