### ISSUE TITLE
Replication lag health check is wrong

### ISSUE THREAD

**Issue by mrkurt** [fly-apps/postgres-ha#30]
Repl lag checks should only run against the primary, I tried to build them into the replicas and that was not a good choice. :)

These checks will be important for future app work. We need to be able to tell our proxy to stop serving traffic to apps in a region with a stale replica. So adding multiple "checks" to the list for each replica might make sense.

**Comment by davissp14** [comment]
Yeah, I think this will be an easy fix. 

We can get the current WAL position of master by hitting `pg_current_wal_lsn()`, then we can just calculate the diff by comparing it with the last reported WAL position replayed or flushed per client.  I'm still going back and forth on whether to use the replay or flush position though.

I guess the question is how we want measure replication lag?  Do we care more about how long it takes changes to to get flushed to disk on a given Standby, or when the changes are actually queryable?  One thing to note about replay is that there are a number of replication conflicts that could affect the result.

**Comment by davissp14** [comment]
```
`select client_addr,
		(pg_current_wal_lsn()-flush_lsn::pg_lsn) AS replication_lag
		(pg_current_wal_lsn()-replay_lsn::pg_lsn) AS real_lag,
		from pg_stat_replication;`
```
I think this may do the trick.

**Comment by davissp14** [comment]
This has been addressed here: https://github.com/fly-apps/postgres-ha/blob/f33491928fa1571ee1fd422d8466fbfc47ab23ad/pkg/flycheck/pg.go#L124

New PG apps will have these changes, but I haven't rolled them out everywhere yet.
