### ISSUE TITLE
Postgres 14 support?

### ISSUE THREAD

**Issue by jadbox** [fly-apps/postgres-ha#49]
Hey folks, are there any updates on when v14 will be available?

**Comment by davissp14** [comment]
@jadbox You can target PG 14 when creating a new Postgres.  `flyctl create pg --image-ref flyio/postgres:14` should do the trick.

**Comment by jadbox** [comment]
Thank you! I'll give it a shot

**Comment by ryanwinchester** [comment]
> @jadbox You can target PG 14 when creating a new Postgres. `flyctl create pg --image-ref flyio/postgres:14` should do the trick.

Argument order

```sh
fly pg create --image-ref flyio/postgres:14
```

**Comment by davissp14** [comment]
Thanks, sorry for the typo.  Also, PG 14.1 has been made the default version.  So no need to do this for PG14 going forward.

**Comment by ryanwinchester** [comment]
> Thanks, sorry for the typo. Also, PG 14.1 has been made the default version. So no need to do this for PG14 going forward.

If I don't do this, I get `v0.0.5`. If I do this I get `v0.0.9`.

**Comment by davissp14** [comment]
@ryanwinchester That is certainly a bug.  Let me dig into that.

**Comment by ryanwinchester** [comment]
@davissp14 I don't know which images are supplied, I'm just following instructions/docs.

**Comment by davissp14** [comment]
@ryanwinchester You can see which image you're on by running: `flyctl image show --app <app-name>`

**Comment by ryanwinchester** [comment]
> @ryanwinchester You can see which image you're on by running: `flyctl image show --app <app-name>`

```
Registry   = registry-1.docker.io
  Repository = flyio/postgres
  Tag        = 14.1
  Version    = v0.0.9
  Digest     = sha256:ea54d08a4e97a772ca033cd02d852d4a96d023978669ee148a9d439f30d50685
```
