### ISSUE TITLE
How to add extensions such as timescaledb?

### ISSUE THREAD

**Issue by nunofgs** [fly-apps/postgres-ha#67]
Any plans for easily adding extensions to the cluster?

**Comment by dysinger** [comment]
I also want this. I've been scouring the internet for info on adding extensions. It's common to need a little bit of packaging installed and some modifications to postgresql.conf to make it work. I'm not certain how this would be handled with fly's canned postgres

**Comment by dysinger** [comment]
It's not encouraging that this issue has sat unanswered since Apr 1 :(

**Comment by tekacs** [comment]
Same question here -- was looking to use `pglogical` (which is easily pulled from apt) to migrate from Google Cloud SQL, but the current situation would involve disabling the `fly postgres` commands by making a custom image. Would really appreciate some way to set the instance up with extension installation.

**Comment by amrnt** [comment]
why not to take a look at https://github.com/fly-apps/postgres-ha/pull/75? I have timescaledb up in no time!

The only backward is not being able to use `fly pg` commands

**Comment by davissp14** [comment]
https://github.com/fly-apps/postgres-ha/pull/75
