### ISSUE TITLE
Single Node in Local Development

### ISSUE THREAD

**Issue by tyrauber** [fly-apps/postgres-ha#98]
Is it possible to enable single node and disable consul in local development through an ENV variable?

I'd love to be able to disable consul locally to develop around the image, but it seems that consul is required.

> Panic: FLY_CONSUL_URL or CONSUL_URL are required

Issue #48 and flyctl/pull/625 seem to indicate that this was done through the fly api by setting a `vmSizeName` of `''`. Is it possible to replicate this functionality locally with an ENV variable?

**Comment by davissp14** [comment]
Nope, if you're just looking for a simple single node setup that runs without consul, you can look at: https://github.com/fly-apps/postgres-standalone

**Comment by tyrauber** [comment]
Alright, Thank @davissp14, appreciate the response. I'll just swap the image with `flyio/postgres-standalone:14.1` when developing and test locally. Thank you.

**Comment by davissp14** [comment]
@tyrauber We no longer provide support for those images.  That being said, you should clone/fork the repo and deploy manually.
